from django.test import TestCase

from base.tests import BaseTestCase
from census.models import Census
from voting.models import Voting
import json
from django.contrib.auth.models import User


# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities



# Create your tests here.

class BoothTestCase(BaseTestCase):

    def setUp(self):
        super().setUp()

    def tearDown(self):
        super().tearDown()

    def get_or_create_user(self, pk):
        user, _ = User.objects.get_or_create(pk=pk)
        user.username = 'user{}'.format(pk)
        user.set_password('qwerty')
        user.save()
        return user

    def testGetVotings(self):
        userNuevo = self.get_or_create_user(1)
        data = {
            User: userNuevo
        }
        response = self.client.post('/booth/votaciones/', data)
        self.assertEqual(response.status_code, 200)

    def testBooth(self):
        userNuevo = self.get_or_create_user(1)
        data = {
            User: userNuevo
        }
        self.login(user = userNuevo.username)
        response = self.client.get('/booth/', data)
        self.assertEqual(response.status_code, 200)
        

"""
class TestLoginBooth():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_loginBooth(self):
    self.driver.get("http://127.0.0.1:8000/booth/")
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("usuarioSelenium")
    self.driver.find_element(By.ID, "password").send_keys("decide123")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
"""
  
